### PR TITLE
Fixed Sign message through Ledger and Ledger with Phantom

### LINKED ISSUE #44: User not able to Sign message through Ledger and  Ledger with Phantom
Error when User trying to sign the message to verify wallet balance through phantom with ledger or ledger itself

Image

Image

**For more info**

[Link to the Discord thread](https://discord.com/channels/1004566368475164683/1363535038230036665)

### PR DESCRIPTION
**Pull request by shubhiscoding**
The signMessage() feature is not currently supported when using Phantom in combination with a Ledger hardware wallet. so I added an option to sign a dummy transaction to verify wallet ownership when signing with Ledger.

NOTE: I didn't have a hardware wallet so I didn't tested it with ledger, but I did test the dummy transaction flow with a transaction through phantom.

This pull request was created for https://app.gib.work/bounties/d501973b-dd07-43ec-94fc-0fd1cf7db629 in an attempt to solve a bounty #44 . Payment for the bounty is immediately sent to the contributor after merge.

closes #44

### CODE REVIEW

**Comment by shubhiscoding** [comment]
Updated the PR to include the check for wallet ownership when transaction signed by a Ledger  or Phantom using Ledger

my fix is inspired by: https://github.com/solana-labs/solana/issues/21366#issuecomment-1194310677

**Comment by shubhiscoding** [comment]
Merge conflict solved!
@anthonyliriano The PR is ready for review!

File: work-verify/src/utils/action.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
+"use server";
+
+import { Connection } from "@solana/web3.js";
+
+export const confirmTransaction = async (signature: string, blockhash: string, lastValidBlockHeight: number)=>{
+    try{
+        const solConnection = new Connection(process.env.SOLANA_RPC_URL || "https://api.mainnet-beta.solana.com");
+        console.log(process.env.SOLANA_RPC_URL);
```
Comment (Redfox) [inline work-verify/src/utils/action.ts:8]: can you pls remove this `SOLANA_RPC_URL` log?

**Comment by shubhiscoding** [comment]
Hey! dropping this here just in case, if you'd like to vouch for me:
https://app.gib.work/p/shubh
